category:
    resource: '@PimApiBundle/Resources/config/routing/category.yml'
    prefix: /rest/v1/categories

family:
    resource: '@PimApiBundle/Resources/config/routing/family.yml'
    prefix: /rest/v1/families

attribute:
    resource: '@PimApiBundle/Resources/config/routing/attribute.yml'
    prefix: /rest/v1/attributes

endpoint:
    resource: '@PimApiBundle/Resources/config/routing/endpoint.yml'
    prefix: /rest/v1
