pim_api_rest_category_list:
    path: /categories
    defaults: { _controller: pim_api.controller.rest.category:listAction, _format: json }
    methods: [GET]

pim_api_rest_category_get:
    path: /categories/{code}
    defaults: { _controller: pim_api.controller.rest.category:getAction, _format: json }
    methods: [GET]
