pim_api_rest_family_list:
    path: /families
    defaults: { _controller: pim_api.controller.rest.family:listAction, _format: json }
    methods: [GET]

pim_api_rest_family_get:
    path: /families/{code}
    defaults: { _controller: pim_api.controller.rest.family:getAction, _format: json }
    methods: [GET]
